package:
    name: pulseportraiture
    version: {{ GIT_DESCRIBE_TAG | replace("v","") }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

source:
    git_url: https://github.com/pennucci/PulsePortraiture.git
    git_tag: py3 # [py3k] 

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - psrchive
        - matplotlib
        - lmfit
        - pywavelets
        - file

test:
    imports:
        - pplib
        - pptoaslib
    commands:
        - pptoas.py -h

about:
    home: https://github.com/pennucci/PulsePortraiture

